Repository Graduate-of-LEAP/Gigley, pull requests merged in 2024-10, with the labels that each got.

#32 24-header
  fe/components.json
  fe/package-lock.json
  fe/package.json
  fe/src/app/globals.css
  fe/src/components/assets/Header.tsx
  fe/src/components/homepage-components/HeroSection.tsx
  fe/src/components/ui/button.tsx
  fe/src/components/ui/form.tsx
  fe/src/components/ui/input.tsx
  fe/src/components/ui/label.tsx
  fe/src/lib/utils.ts
  fe/tailwind.config.ts
Labels: new component

#69 feat(frontend): PopularServices
  fe/package-lock.json
  fe/package.json
  fe/src/components/homepage-components/PopularServices.tsx
  fe/src/components/ui/tabs.tsx
Labels: new component

#67 17-yourtodolist
  fe/public/picture/Handy.png
  fe/src/components/ServicesPage-components/YourTodoList.tsx
Labels: new component

#76 user-account
  fe/src/app/clients-side/UserAccount/Account-Balance/page.tsx
  fe/src/app/clients-side/UserAccount/Account-Security/page.tsx
  fe/src/app/clients-side/UserAccount/Billing-Info/page.tsx
  fe/src/app/clients-side/UserAccount/Business-Information/page.tsx
  fe/src/app/clients-side/UserAccount/Cancel-a-Task/page.tsx
  fe/src/app/clients-side/UserAccount/Delete-Account/page.tsx
  fe/src/app/clients-side/UserAccount/Notifications/page.tsx
  fe/src/app/clients-side/UserAccount/Password/page.tsx
  fe/src/app/clients-side/UserAccount/Profile/page.tsx
  fe/src/app/clients-side/UserAccount/Transactions/page.tsx
  fe/src/components/SecondOfFindTasker-components/TaskerIntroComponent.tsx
  fe/src/components/UserAccount-components/AccountSideBar.tsx
  fe/src/components/UserAccount-components/DeleteAccountDialog.tsx
  fe/src/components/UserAccount-components/EditDialog.tsx
  fe/src/components/ui/dialog.tsx
Labels: new component

#80 75 create taskers login and register
  be/src/controllers/tasker/login-tasker.controller.ts
  be/src/controllers/tasker/register-tasker.controller.ts
  be/src/controllers/tasker/tasker.controller.ts
  be/src/index.ts
  be/src/middlewares/auth.middlewares.ts
  be/src/models/tasker.schema.ts
  be/src/routes/tasker.router.ts
  fe/package-lock.json
  fe/package.json
  fe/src/app/layout.tsx
  fe/src/components/BecomeTasker-components/FlexibleWork.tsx
  fe/src/components/TaskerLogin.tsx
  fe/src/components/TaskerRegister.tsx
  fe/src/components/assets/Header.tsx
  fe/src/components/context/auth.taskerProvider.tsx
Labels: backend

#83 filter-sidebar
  fe/package-lock.json
  fe/package.json
  fe/src/app/clients-side/SecondOfFindTasker/page.tsx
  fe/src/components/SecondOfFindTasker-components/DescriptionOfSecond.tsx
  fe/src/components/SecondOfFindTasker-components/FilterSideBar.tsx
  fe/src/components/SecondOfFindTasker-components/MainBody.tsx
  fe/src/components/SecondOfFindTasker-components/SortedBy.tsx
  fe/src/components/assets/Container.tsx
  fe/src/components/assets/TaskerProfileCard.tsx
  fe/src/components/ui/dialog.tsx
  fe/src/components/ui/slider.tsx
Labels: new component

#100 97 complete dashboard full
  be/src/controllers/task/create-task.controller.ts
  be/src/controllers/task/get-task.controller.ts
  be/src/controllers/task/notification.controller.ts
  be/src/controllers/task/update-taskStatus.controller.ts
  be/src/controllers/tasker/tasker.controller.ts
  be/src/index.ts
  be/src/models/task.schema.ts
  be/src/routes/task.router.ts
  fe/src/app/tasker-side/My-tasks/page.tsx
  fe/src/app/tasker-side/TaskerDashboard/page.tsx
  fe/src/components/My-tasks-components/NotificationModal.tsx
  fe/src/components/My-tasks-components/my-task.tsx
  fe/src/components/My-tasks-components/task-card.tsx
  fe/src/components/TaskerDashboard-components/DashboardHeader.tsx
  fe/src/components/TaskerDashboard-components/DashboardLayout.tsx
  fe/src/components/TaskerDashboard-components/DashboardSidebar.tsx
  fe/src/components/context/auth.taskerProvider.tsx
Labels: bug

#102 fixed problem of login and register
  be/src/controllers/tasker/register-tasker.controller.ts
  be/src/controllers/tasker/submit-tasker.controller.ts
  be/src/models/tasker.schema.ts
  fe/src/components/TaskerRegister.tsx
  fe/src/components/context/auth.taskerProvider.tsx
Labels: bug

#105 User middleware, getme done
  be/src/controllers/tasker/login-tasker.controller.ts
  be/src/controllers/user/get-me.controller.ts
  be/src/controllers/user/login-user.controller.ts
  be/src/middlewares/auth.middlewares.ts
  be/src/routes/user.router.ts
  fe/src/components/assets/Header.tsx
  fe/src/components/context/auth.customerProvider.tsx
Labels: documentation

#109 done
  be/src/controllers/MainCategory/get-mainCategory.controller.ts
  be/src/controllers/subCategory/get-all-subcategory.controller.ts
  be/src/index.ts
  be/src/middlewares/auth.middlewares.ts
  fe/src/app/clients-side/ServicesPage/page.tsx
  fe/src/components/ServicesPage-components/HireTasker.tsx
  fe/src/components/assets/Header.tsx
  fe/src/components/homepage-components/HeroSection.tsx
  fe/src/components/homepage-components/PopularServices.tsx
Labels: documentation
